### ISSUE TITLE
Consider adding Tailwind config to npm scripts

### ISSUE THREAD

**Issue by taylorbryant** [kriswep/cra-tailwindcss#1]
Hey, dude! First off, thank you so much for making this and writing the article. I've been using Tailwind with Gulp for the past couple of months and the move to React left me scratching my head a bit. This was a ton of help!

I was wondering if you had considered passing the Tailwind config into the npm scripts. After seeing my changes to **tailwind.js** not reflected in my CSS, it took me some digging around to realize that the config file is not passed into the Tailwind `build` command.

To do this, you would just need to add `-c ./tailwind.js` to the **start** and **build** scripts.

Thanks! 🎉

**Comment by kriswep** [comment]
You're totally right. Thought Tailwindcss cli would pick that config file up by default, but it seems it won't.

Either way, I changed the script setup in this repo and in my article.

Thanks for bringing that to my attention.
