### ISSUE TITLE
Adding Purgecss

### ISSUE THREAD

**Issue by taylorbryant** [kriswep/cra-tailwindcss#2]
Hey, I was curious if you were interested in adding Purgecss to the **prebuild** script. I did something similar with a Gatsby starter I built yesterday: https://github.com/taylorbryant/gatsby-starter-tailwind/blob/master/package.json. If so, I'd be glad to submit a PR with the necessary changes. Thanks!

**Comment by kriswep** [comment]
Honestly, rather not. The purpose of this repo is to serve as a showcase for adding tailwind to a CRA project. Not being a full featured boilerplate.

That being said, I would a chapter outock/`where to go from here` in the readme could be beneficial. 
If you would add a PR towards the readme how to add purgecss and what the benefits are, that would be appreciated.

**Comment by kriswep** [comment]
Closing this for now.
If somebody wants to add a note to the readme regardning purgecss and advanced setup, I#d accept a PR for that
