### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HemalR** [kriswep/cra-tailwindcss#3]
Thanks for the great write-up!

Question: Does using tailwind with styled components mean that there is no need to use purge-css?

And an aside - I tried adding this in as a blog comment but I kept getting the 'Log-in' button (even after logging in with Github). Just an FYI in case it helps. Let me know if a gif would be helpful.

**Comment by kriswep** [comment]
I guess you're asking about the tailwind with styled components setup, which I demoed [here](https://github.com/kriswep/cra-tailwindcss-in-js). 
Yes, in that case you wouldn't need purgecss, as that is handled by the macro setup.

Thanks for the info about the comments, sometimes the login server needs quite some time to wake up. You can just add a comment in GitHub [here](https://github.com/kriswep/wetainment/issues/23) as  well.

Glad it helped, if you have further questions just ask.

**Comment by HemalR** [comment]
Thanks for the quick response!
